directory: /Volumes/media/Music/raul_music 
library: /Volumes/media/Music/raul_music.db
import:
  copy: yes
  quiet_fallback: asis
paths:
  default: $albumartist/$album%aunique{}/$title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album$aunique{}/$title
plugins: fetchart embedart convert info spotify
ui:
  color: no
fetchart:
  # docs: https://beets.readthedocs.io/en/stable/plugins/fetchart.html
  auto: yes
  #cautious: yes
  #cover_names: []
  minwidth: 500
  maxwidth: 500
  quality: 0 # default
  max_filesize: 0 # disabled
  enforce_ratio: 10px
  sources: spotify itunes coverart amazon albumart filesystem
  deinterlace: yes
  cover_format: JPEG 
spotify:
  source_weight: 1.0
musicbrainz:
  source_weight: 0.0
  enabled: no
embedart:
  auto: yes
  compare_threshold: 0
  ifempty: no
convert:
  auto: no
  auto_keep: no 
  copy_album_art: yes
  album_art_maxwidth: 500
  dest: /Volumes/media/Music/sync_to_phone
  embed: yes
  never_conver_lossy_files: yes
  format: mp3
  formats:
    mp3: ffmpeg -i $source -y -vn -b:a 320k $dest
